### ISSUE TITLE
Favorites error

### ISSUE THREAD

**Issue by skarllot** [ianloic/rdio-export#2]
Should have hundreds of favorites but couldn't get none.

```
Migrating 0 favorites for Fabricio Godoy
Traceback (most recent call last):
  File "rdio-export.py", line 117, in <module>
    migrate_favorites(args.rdio_username)
  File "rdio-export.py", line 110, in migrate_favorites
    for match in matched_tracks:
  File "/home/fgodoy/Projects/External/rdio-export/match.py", line 228, in match_tracks
    percentage = int(100 * count / float(num_tracks))
ZeroDivisionError: float division by zero
```

**Comment by yns88** [comment]
This is because it uses `user['trackCount']` to compute num_tracks, which is a deprecated field that was just recently broken. I'd like to import my Favorites to Google Play, so I'll see if I can post a bugfix.

**Comment by ghost** [comment]
Hit he same issue an hour ago. My quick fix, I changed line 109 of rdio-export.py to:

`matched_tracks = match_tracks(list(rdio_tracks), 1, pm)`

This means the percentage complete won't work, but you won't divide by zero. And I had to wrap rdio_tracks in a list() for some reason to turn it from a generator into a list or else the match_tracks function wasn't processing it correctly. I'm not a python guru so this was all very hacky.

**Comment by yns88** [comment]
I just posted a pull request that will omit the total and percentage calculations from the Favorites import: https://github.com/ianloic/rdio-export/pull/4

**Comment by ianloic** [comment]
I've got a better solution in the works. Sorry for the issue....

**Comment by ianloic** [comment]
Fixed it in https://github.com/ianloic/rdio-export/commit/c74277e8cba6785c631ae68dbbb83548e693b83e

Update and try again. Let me know if you see the issue again.
